// Run: node hq/test-office.cjs. Uses generated test keys, never the owner's key.
'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
assert.equal(scripts.length,1);
const source=scripts[0][1].replace(/\ninstallUI\(\);\s*$/,'');
new vm.Script(scripts[0][1]);
const ctx=vm.createContext({window:{},document:{},location:{hash:''},URLSearchParams,TextDecoder,TextEncoder,atob,btoa,crypto:webcrypto,console});
vm.runInContext(source,ctx);
const h=ctx.window.HQOffice;let count=0;
const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const b64=b=>Buffer.from(b).toString('base64url');
const sample={readOnly:true,mode:'snapshot',observedAt:'2026-01-01T02:00:00Z',issues:[{number:1,title:'Generated test fixture',labels:['ai-review'],lane:'codex',claimedAt:'2026-01-01T00:00:00Z',claimEndedAt:'2026-01-01T01:30:00Z',pr:2}]};
(async()=>{
 test('label claim does not assert executing',()=>assert.equal(h.stateOf({labels:['ai-running']}),'claimed'));
 test('blocked record',()=>assert.equal(h.stateOf({labels:['blocked']}),'blocked'));
 test('review record',()=>assert.equal(h.stateOf({labels:['claude-review']}),'review'));
 test('closed record',()=>assert.equal(h.stateOf({state:'closed',labels:[]}),'done'));
 test('queue record',()=>assert.equal(h.stateOf({labels:['claude-ready']}),'queued'));
 test('no task stays unknown',()=>assert.equal(h.stateOf(null),'unknown'));
 test('Opus maps to specialist seat',()=>assert.equal(h.laneOf({lane:'claude',model:'opus'}),'opus'));
 test('default Claude lane is not an assumed model',()=>assert.equal(h.laneOf({lane:'claude'}),'claude'));
 test('Fable maps separately',()=>assert.equal(h.laneOf({model:'fable'}),'fable'));
 test('missing duration is not fabricated',()=>assert.equal(h.elapsed(null),'측정 안 됨'));
 test('invalid duration is not fabricated',()=>assert.equal(h.elapsed(NaN),'측정 안 됨'));
 test('negative duration is rejected',()=>assert.equal(h.elapsed(-1),'측정 안 됨'));
 test('readable hours minutes seconds',()=>assert.equal(h.elapsed(8100000),'02:15:00'));
 vm.runInContext('data='+JSON.stringify(sample),ctx);
 test('ended claim uses recorded end, not wall clock',()=>assert.equal(h.duration(sample.issues[0]),5400000));
 test('open claim stops at snapshot observation',()=>assert.equal(h.duration({...sample.issues[0],claimEndedAt:null}),7200000));
 test('missing start remains unknown',()=>assert.equal(h.duration({}),null));
 test('inverted timestamps rejected',()=>assert.equal(h.duration({claimedAt:'2026-01-03T00:00:00Z'}),null));
 test('valid snapshot shape',()=>assert.equal(h.validateData(sample).mode,'snapshot'));
 test('mutable payload rejected',()=>assert.throws(()=>h.validateData({...sample,readOnly:false})));
 test('missing observation rejected',()=>assert.throws(()=>h.validateData({...sample,observedAt:null})));
 test('invalid issue ID rejected',()=>assert.throws(()=>h.validateData({...sample,issues:[{...sample.issues[0],number:-1}]})));
 test('invalid PR ID rejected',()=>assert.throws(()=>h.validateData({...sample,issues:[{...sample.issues[0],pr:'javascript:alert(1)'}]})));
 test('invalid labels rejected',()=>assert.throws(()=>h.validateData({...sample,issues:[{...sample.issues[0],labels:[{}]}]})));
 test('text escaping covers HTML payload',()=>assert.equal(vm.runInContext("esc('<img src=x onerror=alert(1)>')",ctx),'&lt;img src=x onerror=alert(1)&gt;'));
 const key=webcrypto.getRandomValues(new Uint8Array(32)),iv=webcrypto.getRandomValues(new Uint8Array(12));
 const ck=await webcrypto.subtle.importKey('raw',key,{name:'AES-GCM'},false,['encrypt']);
 const cipher=await webcrypto.subtle.encrypt({name:'AES-GCM',iv},ck,new TextEncoder().encode(JSON.stringify(sample)));
 const record={version:1,algorithm:'AES-256-GCM',iv:b64(iv),data:b64(cipher)};
 const result=await h.decryptRecord(record,b64(key));
 test('AES-GCM round trip with real generated key',()=>assert.equal(result.issues[0].title,sample.issues[0].title));
 await assert.rejects(()=>h.decryptRecord(record,b64(new Uint8Array(32))));count++;console.log('PASS wrong key rejected');
 let altered=Buffer.from(cipher);altered[3]^=16;
 await assert.rejects(()=>h.decryptRecord({...record,data:b64(altered)},b64(key)));count++;console.log('PASS tampered ciphertext rejected');
 await assert.rejects(()=>h.decryptRecord({...record,version:99},b64(key)));count++;console.log('PASS unknown encryption version rejected');
 for(const mobile of [true,false]){
  let metrics=vm.runInContext(`(()=>{const b=buildOffice(${mobile});return {rooms:b.rooms.length,actors:b.actors.length,finite:b.shape.opaque.every(Number.isFinite)&&b.shape.glass.every(Number.isFinite)&&b.actors.every(a=>a.shape.opaque.every(Number.isFinite)),aligned:b.shape.opaque.length%13,triangles:b.shape.opaque.length/39};})()`,ctx);
  test((mobile?'portrait':'desktop')+' has eight authored rooms',()=>assert.equal(metrics.rooms,8));
  test((mobile?'portrait':'desktop')+' has eight volumetric characters',()=>assert.equal(metrics.actors,8));
  test((mobile?'portrait':'desktop')+' finite GPU vertices',()=>assert.equal(metrics.finite,true));
  test((mobile?'portrait':'desktop')+' bounded static geometry',()=>assert.ok(metrics.triangles<40000&&metrics.aligned===0));
 }
 test('matrix inverse round trip',()=>{const p=vm.runInContext('M.point(M.inverse(M.mul(M.ortho(-10,10,-8,8,1,100),M.look([11,25,32],[0,1,0]))),M.point(M.mul(M.ortho(-10,10,-8,8,1,100),M.look([11,25,32],[0,1,0])),[2,3,-4]))',ctx);assert.ok(Math.abs(p[0]-2)<1e-6&&Math.abs(p[1]-3)<1e-6&&Math.abs(p[2]+4)<1e-6);});
 test('real WebGL canvas, no photograph background',()=>{assert.match(html,/<canvas id="office"/);assert.doesNotMatch(html,/<img\b|data:image\//i);});
 test('no external scripts or libraries',()=>assert.doesNotMatch(html,/<script[^>]*\bsrc=|https?:\/\/[^"']+\.js/));
 test('same-origin CSP and referrer protection',()=>{assert.match(html,/connect-src 'self'/);assert.match(html,/name="referrer" content="no-referrer"/);});
 test('no tracking or persistent key storage',()=>assert.doesNotMatch(html,/localStorage|sessionStorage|document\.cookie|sendBeacon/));
 test('WebGL failure is explicit and still offers records',()=>{assert.match(html,/webglcontextlost/);assert.match(html,/function fail3D/);assert.match(html,/data-fallback/);});
 test('paused hidden-page polling and animation',()=>{assert.match(html,/if\(!document\.hidden\)loadData/);assert.match(html,/if\(document\.hidden\)return/);});
 test('claim timer is not an invented completion percentage',()=>assert.doesNotMatch(html,/출시 준비도|progress:\s*\d|now-1000|Date\.now\(\)-start/));
 test('old request cannot reveal data after key removal',()=>{assert.match(html,/epoch!==requestEpoch/);assert.match(html,/requestEpoch\+\+;aborter\?\.abort/);});
 console.log(`OFFICE CORE: ${count}/${count} PASS`);
})().catch(e=>{console.error(e);process.exitCode=1;});
