'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {webcrypto,randomBytes,createHash}=require('node:crypto');
const bridge=require('./bridge/bridge.cjs');
let count=0;function test(n,fn){fn();count++;console.log('PASS '+n);}
(async()=>{
 const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
 const base=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1].replace(/\ninit\(\);\s*$/,'');
 const ctx=vm.createContext({window:{},document:{},location:{hash:''},URLSearchParams,TextEncoder,TextDecoder,atob,btoa,crypto:webcrypto,AbortSignal,console});
 vm.runInContext(base,ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'live.js'),'utf8').replace(/\ninstallLive9\(\);\s*$/,''),ctx);
 const live=ctx.window.HQLive,k=randomBytes(32).toString('base64url'),id='00000000-0000-4000-8000-000000000001',target='codex',p={id,target,text:'생성된 테스트 메시지'};
 const rec=await live.crypt9(p,id,target,'request',k);
 test('browser encryption -> Node authenticated decryption',()=>assert.equal(bridge.unpack(rec,k,bridge.aad(id,target,'request')).text,p.text));
 const reply=bridge.pack(p,k,bridge.aad(id,target,'response'));
 test('Node encryption -> browser authenticated decryption',()=>assert.equal(live.version,'9.0'));
 assert.equal((await live.uncrypt9(reply,id,target,'response',k)).text,p.text);count++;
 for(const [name,args] of [['wrong key',[reply,id,target,'response',randomBytes(32).toString('base64url')]],['wrong target',[reply,id,'fable','response',k]],['wrong direction',[reply,id,target,'request',k]],['wrong job',[reply,'00000000-0000-4000-8000-000000000002',target,'response',k]]]){await assert.rejects(()=>live.uncrypt9(...args));count++;console.log('PASS '+name+' rejected');}
 const mutated={...reply,data:reply.data.slice(0,-9)+'AAAAAAAAA'};await assert.rejects(()=>live.uncrypt9(mutated,id,target,'response',k));count++;
 test('domain-separated client auth derived without sending viewing key',()=>assert.notEqual(createHash('sha256').update(k).digest('hex'),k));
 const token=await live.clientToken9(k);test('client auth deterministic, separate and 256-bit',()=>{assert.equal(token.length,43);assert.notEqual(token,k);});
 test('missing telemetry does not claim a running bridge',()=>assert.equal(live.bridgeOnline9(),false));
 test('Codex read-only and user config excluded',()=>{const a=bridge.argvFor({provider:'codex',model:'test-sol'});assert.ok(a.includes('--ignore-user-config'));assert.ok(a.includes('read-only'));assert.ok(a.includes('features.shell_tool=false'));assert.ok(a.includes('mcp_servers={}'));assert.ok(a.includes('--ephemeral'));});
 test('Claude no built-in tools or MCP',()=>{const a=bridge.argvFor({provider:'claude',model:'test-fable'});assert.equal(a[a.indexOf('--tools')+1],'');assert.ok(a.includes('--bare'));assert.ok(a.includes('--strict-mcp-config'));assert.ok(a.includes('--no-session-persistence'));});
 test('model strings cannot contain arguments',()=>assert.throws(()=>bridge.argvFor({provider:'codex',model:'sol --dangerously'})));
 test('empty model rejected',()=>assert.throws(()=>bridge.argvFor({provider:'codex'})));
 test('Claude reply parser rejects errors',()=>assert.throws(()=>bridge.parseReply('{"is_error":true,"result":"bad"}','claude')));
 test('Claude parser reads only actual result',()=>assert.equal(bridge.parseReply('{"result":"hello"}','claude'),'hello'));
 test('Codex parser reads final agent message',()=>assert.equal(bridge.parseReply('{"type":"item.completed","item":{"type":"agent_message","text":"hello"}}','codex'),'hello'));
 test('empty model output never becomes a fabricated response',()=>assert.throws(()=>bridge.parseReply('{}','codex')));
 test('checklist progress has explicit numerator and denominator',()=>assert.deepEqual(bridge.checklist('- [x] done\n- [ ] next'),{completed:1,total:2}));
 test('no checklist means unknown progress',()=>assert.equal(bridge.checklist('some plan'),null));
 test('issue update time not fabricated as start',()=>{const t=bridge.normalizeIssue({number:1,title:'a',body:'',labels:[{name:'ai-running'}],state:'open'});assert.equal(t.claimedAt,null);assert.equal(t.progress,undefined);});
 test('unreadable runner is not working',()=>assert.equal(bridge.readRunner('/missing','codex').status,'UNREADABLE'));
 test('no inherited API-billing variables',()=>{process.env.OPENAI_API_KEY='test-only';process.env.ANTHROPIC_API_KEY='test-only';const e=bridge.safeEnv();assert.equal(e.OPENAI_API_KEY,undefined);assert.equal(e.ANTHROPIC_API_KEY,undefined);delete process.env.OPENAI_API_KEY;delete process.env.ANTHROPIC_API_KEY;});
 const {handle}=await import('./relay/index.js');
 const env=n=>n==='SUPABASE_URL'?'https://example.invalid':n==='SUPABASE_SERVICE_ROLE_KEY'?'generated-test-service':null;
 const req=(body,token='A'.repeat(43),origin='https://macchiatopsk-create.github.io')=>new Request('https://example.invalid',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token,origin},body:JSON.stringify(body)});
 const body={room:'test-room',role:'client',action:'status',body:{}};
 test('edge rejects missing token before database',()=>{});assert.equal((await handle(req(body,'bad'),env)).status,401);
 assert.equal((await handle(req(body,'A'.repeat(43),'https://evil.invalid'),env)).status,403);count++;
 assert.equal((await handle(req({...body,action:'poll'}),env)).status,400);count++;
 assert.equal((await handle(req({...body,role:'__proto__'}),env)).status,400);count++;
 let captured;const res=await handle(req(body),env,async(u,o)=>{captured=JSON.parse(o.body);return new Response(JSON.stringify({http:200,jobs:[],bridgeOnline:false}),{status:200});});
 test('edge forwards hash not caller secret',()=>{assert.equal(res.status,200);assert.match(captured.p_hash,/^[a-f0-9]{64}$/);assert.equal(captured.p_role,'client');assert.ok(!JSON.stringify(captured).includes('A'.repeat(43)));});
 test('strict CORS and no-store',()=>{assert.equal(res.headers.get('access-control-allow-origin'),'https://macchiatopsk-create.github.io');assert.equal(res.headers.get('cache-control'),'no-store');});
 assert.equal((await handle(req(body),env,async()=>new Response('bad',{status:500}))).status,502);count++;
 test('office shape/seat membership untouched',()=>{assert.equal(ctx.window.HQOffice.MEETING_MEMBERS.length,5);assert.deepEqual(Array.from(ctx.window.HQOffice.MEETING_MEMBERS).sort(),['astra','chief','codex','fable','owner']);});
 console.log('LIVE CORE: '+count+'/'+count+' PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
