// node hq/test-office.cjs — isolated generated fixtures; no private viewing keys.
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {webcrypto,createHash}=require('node:crypto');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const blocks=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
assert.equal(blocks.length,1);new vm.Script(blocks[0][1]);
const ctx=vm.createContext({window:{},document:{},location:{hash:''},URLSearchParams,TextDecoder,TextEncoder,atob,btoa,crypto:webcrypto,console});
vm.runInContext(blocks[0][1].replace(/\ninit\(\);\s*$/,''),ctx);
const api=ctx.window.HQOffice;let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const b64=b=>Buffer.from(b).toString('base64url');
const sample={readOnly:true,mode:'snapshot',observedAt:'2026-01-01T02:00:00Z',issues:[{number:1,title:'Generated fixture',labels:['ai-review'],lane:'codex',claimedAt:'2026-01-01T00:00:00Z',claimEndedAt:'2026-01-01T01:30:00Z',pr:2}]};
(async()=>{
 test('claimed does not mean executing',()=>assert.equal(api.stateOf({labels:['ai-running']}),'claimed'));
 test('blocked label',()=>assert.equal(api.stateOf({labels:['blocked']}),'blocked'));
 test('review label',()=>assert.equal(api.stateOf({labels:['claude-review']}),'review'));
 test('closed issue',()=>assert.equal(api.stateOf({state:'closed',labels:[]}),'done'));
 test('queue label',()=>assert.equal(api.stateOf({labels:['claude-ready']}),'queued'));
 test('absent task unknown',()=>assert.equal(api.stateOf(null),'unknown'));
 test('Opus explicit routing',()=>assert.equal(api.laneOf({lane:'claude',model:'opus'}),'opus'));
 test('unknown Claude model not guessed',()=>assert.equal(api.laneOf({lane:'claude'}),'claude'));
 test('Fable separate',()=>assert.equal(api.laneOf({model:'fable'}),'fable'));
 test('Luna support lane',()=>assert.equal(api.laneOf({model:'luna'}),'support'));
 test('missing time not fabricated',()=>assert.equal(api.elapsed(null),'측정 안 됨'));
 test('NaN time not fabricated',()=>assert.equal(api.elapsed(NaN),'측정 안 됨'));
 test('negative time not fabricated',()=>assert.equal(api.elapsed(-1),'측정 안 됨'));
 test('readable hours and minutes',()=>assert.equal(api.elapsed(8100000),'2시간 15분'));
 vm.runInContext('data='+JSON.stringify(sample),ctx);
 test('ended claim stops at recorded end',()=>assert.equal(api.duration(sample.issues[0]),5400000));
 test('open claim stops at snapshot observation',()=>assert.equal(api.duration({...sample.issues[0],claimEndedAt:null}),7200000));
 test('missing start unknown',()=>assert.equal(api.duration({}),null));
 test('inverted time unknown',()=>assert.equal(api.duration({claimedAt:'2026-01-03T00:00:00Z'}),null));
 test('valid immutable snapshot',()=>assert.equal(api.validateData(sample).mode,'snapshot'));
 test('non-read-only data rejected',()=>assert.throws(()=>api.validateData({...sample,readOnly:false})));
 test('absent timestamp rejected',()=>assert.throws(()=>api.validateData({...sample,observedAt:null})));
 test('negative issue rejected',()=>assert.throws(()=>api.validateData({...sample,issues:[{...sample.issues[0],number:-1}]})));
 test('malformed PR rejected',()=>assert.throws(()=>api.validateData({...sample,issues:[{...sample.issues[0],pr:'javascript:alert(1)'}]})));
 test('malformed labels rejected',()=>assert.throws(()=>api.validateData({...sample,issues:[{...sample.issues[0],labels:[{}]}]})));
 test('oversized title rejected',()=>assert.throws(()=>api.validateData({...sample,issues:[{...sample.issues[0],title:'x'.repeat(1001)}]})));
 test('HTML escaped',()=>assert.equal(vm.runInContext("esc('<img src=x onerror=alert(1)>')",ctx),'&lt;img src=x onerror=alert(1)&gt;'));
 const raw=webcrypto.getRandomValues(new Uint8Array(32)),iv=webcrypto.getRandomValues(new Uint8Array(12));
 const ck=await webcrypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt']);
 const encrypted=await webcrypto.subtle.encrypt({name:'AES-GCM',iv},ck,new TextEncoder().encode(JSON.stringify(sample)));
 const record={version:1,algorithm:'AES-256-GCM',iv:b64(iv),data:b64(encrypted)};
 const result=await api.decryptRecord(record,b64(raw));
 test('real AES-GCM roundtrip',()=>assert.equal(result.issues[0].title,sample.issues[0].title));
 await assert.rejects(()=>api.decryptRecord(record,b64(new Uint8Array(32))));count++;console.log('PASS wrong key rejected');
 const changed=Buffer.from(encrypted);changed[3]^=16;
 await assert.rejects(()=>api.decryptRecord({...record,data:b64(changed)},b64(raw)));count++;console.log('PASS altered ciphertext rejected');
 await assert.rejects(()=>api.decryptRecord({...record,version:99},b64(raw)));count++;console.log('PASS unknown envelope rejected');
 await assert.rejects(()=>api.decryptRecord({...record,iv:b64(new Uint8Array(8))},b64(raw)));count++;console.log('PASS incorrect IV rejected');
 test('eight reference rooms',()=>assert.equal(api.TEAMS.length,8));
 for(const team of api.TEAMS)test(team.id+' bounds within artwork',()=>{const [x,y,w,h]=team.box;assert.ok(x>=0&&y>=0&&w>0&&h>0&&x+w<=1112&&y+h<=595);assert.ok(team.center.every(Number.isFinite));});
 test('eight persistent source label masks',()=>{assert.equal((html.match(/class="room-head[ "]/g)||[]).length,8);assert.equal((html.match(/class="room-info[ "]/g)||[]).length,8);});
 test('one local reference image',()=>{assert.equal((html.match(/<img\b/g)||[]).length,1);assert.match(html,/src="\.\/office-art\.avif"/);});
 test('reference asset integrity',()=>{assert.equal(createHash('sha256').update(fs.readFileSync(path.join(__dirname,'office-art.avif'))).digest('hex'),'97335abb3926ccd401451e285a56772d75d3f7279af5c6ca93bbd4058c231976');});
 test('no WebGL substitute',()=>assert.doesNotMatch(html,/<canvas\b|createOfficeRenderer|webgl2/));
 test('art and hotspots share coordinate space',()=>{assert.match(html,/width="1112" height="595"/);assert.match(html,/\$\('office'\)\.style\.transform/);});
 test('no external code or fonts',()=>assert.doesNotMatch(html,/<script[^>]+src=|@import|fonts\.google|cdn\./));
 test('same-origin and referrer policy',()=>{assert.match(html,/connect-src 'self'/);assert.match(html,/name="referrer" content="no-referrer"/);});
 test('no tokens or persistent key storage',()=>assert.doesNotMatch(html,/github_pat_|ghp_|sk-proj-|localStorage|sessionStorage|document\.cookie|sendBeacon/));
 test('snapshot not claimed as live work',()=>{assert.match(html,/실제 실행시간/);assert.match(html,/측정 안 됨/);assert.doesNotMatch(html,/now-1000|Date\.now\(\)-start|progress:\s*\d/);});
 test('stale decryption invalidated on key removal',()=>{assert.match(html,/own!==epoch/);assert.match(html,/epoch\+\+;aborter\?\.abort/);});
 test('hidden-page polling paused',()=>assert.match(html,/if\(!document\.hidden\)loadData/));
 test('art failure explicit',()=>assert.match(html,/\$\('image-error'\)\.hidden=false/));
 console.log(`OFFICE CORE: ${count}/${count} PASS`);
})().catch(e=>{console.error(e);process.exitCode=1;});
